// Rebuilds `world.js` from Natural Earth. Dev-only: the page never loads this.
//
// Run it from this folder when the coastlines need regenerating:
//
//   bun buildWorld.js
//
// It downloads the Natural Earth 1:110m land polygons (public domain) as
// TopoJSON, decodes them into plain longitude and latitude rings, and writes
// `world.js`. See ADR 0003 for why the coastlines ship with the page instead of
// coming from a tile server.
//
// TopoJSON stores its coordinates twice-encoded: quantized to integers against a
// transform, and delta-encoded along each arc. Both have to be undone, in that
// order, or the map comes out as a small smear near the origin.

const SOURCE = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json";

/** Shapes smaller than this many square degrees are dropped. */
const MIN_AREA = 0.6;
/** Two decimals is about one kilometre, which is past what a world map shows. */
const PRECISION = 2;

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}`);
const topology = await response.json();

const { scale, translate } = topology.transform;

// Undo the delta encoding, then the quantization.
const arcs = topology.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});

/** A negative arc index means "walk that arc backwards". */
function ring(indexes) {
  const points = [];
  for (const index of indexes) {
    const arc = index < 0 ? arcs[~index].slice().reverse() : arcs[index];
    // Consecutive arcs share an endpoint, so drop the repeat.
    points.push(...(points.length ? arc.slice(1) : arc));
  }
  return points;
}

/** Shoelace area in square degrees. Only used to rank shapes by size. */
function area(points) {
  let sum = 0;
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    sum += points[j][0] * points[i][1] - points[i][0] * points[j][1];
  }
  return Math.abs(sum / 2);
}

const shapes = [];
for (const geometry of topology.objects.land.geometries) {
  const polygons = geometry.type === "MultiPolygon" ? geometry.arcs : [geometry.arcs];
  // Outer ring only: a lake inside a landmass is not a coastline.
  for (const polygon of polygons) shapes.push(ring(polygon[0]));
}

const kept = shapes.filter((shape) => area(shape) >= MIN_AREA).sort((a, b) => area(b) - area(a));
const round = (value) => Number(value.toFixed(PRECISION));
// Flat runs, because a nested pair array costs about a third more bytes.
const flat = kept.map((shape) => shape.flatMap(([lon, lat]) => [round(lon), round(lat)]));
const points = flat.reduce((total, shape) => total + shape.length / 2, 0);

const file = `// The world's coastlines, so this page draws a map without a tile server.
//
// Source: Natural Earth 1:110m land polygons, via the \`world-atlas\` TopoJSON
// build. Natural Earth is public domain, so these numbers ship with the page.
// Generated by \`buildWorld.js\`; never hand-edit. Outer rings only (no lakes),
// coordinates rounded to ${PRECISION} decimals (about one kilometre), and shapes under
// ${MIN_AREA} square degrees dropped. ${kept.length} shapes, ${points} points. See ADR 0003.
//
// Each shape is a flat run of [lon, lat, lon, lat, ...] in degrees.

/** @type {number[][]} */
export const LAND_SHAPES = [
${flat.map((shape) => `  [${shape.join(",")}],`).join("\n")}
];
`;

await Bun.write(new URL("./world.js", import.meta.url), file);
console.log(`world.js written: ${kept.length} shapes, ${points} points, ${file.length} bytes`);
