// A real slice of the Wikipedia Current Events portal, kept as the parser's spec.
//
// This is the markup `action=parse` returned for 30 August 2026, cut after the
// third category heading. It is real and not hand-written on purpose: the parser
// has to survive the portal's actual nesting, its redirect links, its
// `class="external text"` source links and its non-breaking spaces.
//
// Refresh it only with another real response, never by hand.

export const PORTAL_HTML_2026_08_30 = `<div class="current-events-content description">
<p><b>Armed conflicts and attacks</b>
</p>
<ul><li><a href="/wiki/2026_Iran_war" title="2026 Iran war">2026 Iran war</a>
<ul><li><a href="/wiki/2026_Strait_of_Hormuz_crisis" title="2026 Strait of Hormuz crisis">2026 Strait of Hormuz crisis</a>
<ul><li>A spokesperson for the <a href="/wiki/United_States_Central_Command" title="United States Central Command">United States Central Command</a> reports that the <a href="/wiki/United_States_Armed_Forces" title="United States Armed Forces">U.S. military</a> has launched strikes on two <a href="/wiki/Iranian_Armed_Forces" title="Iranian Armed Forces">Iranian</a> <a href="/wiki/Rocket_launcher" title="Rocket launcher">rocket launchers</a> at <a href="/wiki/Larak_Island" title="Larak Island">Larak Island</a> in the <a href="/wiki/Strait_of_Hormuz" title="Strait of Hormuz">Strait of Hormuz</a> that were used by <a href="/wiki/Islamic_Revolutionary_Guard_Corps" title="Islamic Revolutionary Guard Corps">Islamic Revolutionary Guard Corps</a>, its first strikes against the country since <a href="/wiki/July_2026_United_States_strikes_against_Iran" class="mw-redirect" title="July 2026 United States strikes against Iran">July</a>. <a rel="nofollow" class="external text" href="https://www.axios.com/2026/08/30/us-iran-strike-hormuz-mines">(<i>Axios</i>)</a> <a rel="nofollow" class="external text" href="https://www.nbcnews.com/politics/national-security/us-forces-strike-iranian-rocket-launchers-strait-hormuz-first-military-rcna595194">(NBC News)</a></li>
<li>Iran launches attacks on United States bases in <a href="/wiki/Jordan" title="Jordan">Jordan</a>. <a rel="nofollow" class="external text" href="https://www.reuters.com/world/middle-east/irans-irgc-says-it-launched-attack-two-us-bases-jordan-2026-08-30/">(Reuters)</a></li></ul></li></ul></li>
<li><a href="/wiki/Russo-Ukrainian_war" title="Russo-Ukrainian war">Russo-Ukrainian war</a>
<ul><li><a href="/wiki/Attacks_in_Russia_during_the_Russo-Ukrainian_war_(2022%E2%80%93present)" title="Attacks in Russia during the Russo-Ukrainian war (2022–present)">Attacks in Russia during the Russo-Ukrainian war</a>
<ul><li>A <a href="/wiki/Ukrainian_Air_Defence_Forces" title="Ukrainian Air Defence Forces">Ukrainian missile</a> strike on <a href="/wiki/Belgorod" title="Belgorod">Belgorod</a>, <a href="/wiki/Russia" title="Russia">Russia</a>, kills two people and injures 16 others, according to <a href="/wiki/Belgorod_Oblast" title="Belgorod Oblast">regional</a> acting <a href="/wiki/Governor_of_Belgorod_Oblast" title="Governor of Belgorod Oblast">governor</a> <a href="/wiki/Alexander_Shuvaev" title="Alexander Shuvaev">Alexander Shuvaev</a>. <a rel="nofollow" class="external text" href="https://www.reuters.com/world/missile-attack-kills-two-injures-16-russias-belgorod-authorities-say-2026-08-30/">(Reuters)</a> <a rel="nofollow" class="external text" href="https://english.news.cn/europe/20260831/0618e80ed77f4a0282c21b69122071f7/c.html">(Xinhua)</a></li></ul></li></ul></li>
<li><a href="/wiki/Sudanese_civil_war_(2023%E2%80%93present)" title="Sudanese civil war (2023–present)">Sudanese civil war</a>
<ul><li><a href="/wiki/Kordofan_campaign_(2023%E2%80%93present)" title="Kordofan campaign (2023–present)">Kordofan campaign</a>, <a href="/wiki/Battle_of_Barah" title="Battle of Barah">Battle of Barah</a>
<ul><li><a href="/wiki/Sudan" title="Sudan">Sudan</a>'s doctors network reports that five civilians have been killed and thousands have been displaced during attacks by <a href="/wiki/Rapid_Support_Forces" title="Rapid Support Forces">Rapid Support Forces</a> in <a href="/wiki/Barah,_Sudan" title="Barah, Sudan">Bara</a>, <a href="/wiki/North_Kordofan" title="North Kordofan">North Kordofan</a>. <a rel="nofollow" class="external text" href="https://sudantribune.com/article/318063">(<i>Sudan Tribune</i>)</a></li></ul></li></ul></li>
<li><a href="/wiki/2026_Nigerien_coup_attempt" title="2026 Nigerien coup attempt">2026 Nigerien coup attempt</a>
<ul><li><a href="/wiki/Niger" title="Niger">Niger</a>'s <a href="/wiki/Niger_Armed_Forces#Niger_Army" title="Niger Armed Forces">army</a> says that they have regained control of an airbase after it was attacked by mutinous soldiers yesterday. <a rel="nofollow" class="external text" href="https://www.reuters.com/world/europe/niger-says-it-regains-control-airbase-after-soldiers-mutiny-2026-08-30/">(Reuters)</a></li></ul></li></ul>
<p><b>Disasters and accidents</b>
</p>
<ul><li><a href="/wiki/2026_Indonesia_wildfires" title="2026 Indonesia wildfires">2026 Indonesia wildfires</a>
<ul><li><a href="/wiki/2026_East_Malaysia_haze" title="2026 East Malaysia haze">2026 East Malaysia haze</a>
<ul><li>An <a href="/wiki/Orangutan" title="Orangutan">orangutan</a> named Sampurna is reported to be rescued from a <a href="/wiki/Haze" title="Haze">haze</a> fire zone in <a href="/wiki/Ketapang" title="Ketapang">Ketapang</a>, <a href="/wiki/West_Kalimantan" title="West Kalimantan">West Kalimantan</a>, on <a href="/wiki/Indonesia" title="Indonesia">Indonesia</a>'s <a href="/wiki/Borneo" title="Borneo">Borneo</a> island. <a rel="nofollow" class="external text" href="https://www.reuters.com/business/environment/orangutan-rescued-fire-zone-indonesias-borneo-battles-respiratory-illness-2026-08-30/">(Reuters)</a></li></ul></li>
<li>The <a href="/wiki/Japan_Maritime_Self-Defense_Force" title="Japan Maritime Self-Defense Force">Japanese military</a> ship <a href="/wiki/JS_Kunisaki" title="JS Kunisaki">JS <i>Kunisaki</i></a> departs from a port in <a href="/wiki/Kure,_Hiroshima" title="Kure, Hiroshima">Kure</a>, <a href="/wiki/Hiroshima_Prefecture" title="Hiroshima Prefecture">Hiroshima</a>, to help fight <a href="/wiki/Wildfire" title="Wildfire">wildfires</a> in <a href="/wiki/Indonesia" title="Indonesia">Indonesia</a>. <a rel="nofollow" class="external text" href="https://en.tempo.co/read/2118581/japans-kunisaki-ship-departs-to-help-fight-indonesia-wildfires">(<i>Tempo</i>)</a></li></ul></li>
<li><a href="/wiki/Sinking_of_the_Filo_Jet" title="Sinking of the Filo Jet">Sinking of the Filo Jet</a>
<ul><li>At least eight people are killed and 18 others are missing when a passenger ferry, sailing from <a href="/wiki/Cyprus" title="Cyprus">Cyprus</a> to <a href="/wiki/Turkey" title="Turkey">Turkey</a>, capsizes in the eastern <a href="/wiki/Mediterranean_sea" class="mw-redirect" title="Mediterranean sea">Mediterranean sea</a>. The ship was carrying 259 passengers and 8 crew members, of which 237 people have been rescued. <a rel="nofollow" class="external text" href="https://news.sky.com/story/boat-capsizing-latest-vessel-with-270-people-on-board-capsizes-off-northern-cyprus-13577576">(Sky News)</a> <a rel="nofollow" class="external text" href="https://www.reuters.com/world/europe/boat-with-around-270-people-capsizes-off-north-cyprus-media-says-2026-08-30/">(Reuters)</a></li></ul></li>
<li>The body of the last missing individual aboard a boat capsized on Thursday on <a href="/wiki/Mapanuepe_Lake" title="Mapanuepe Lake">Mapanuepe Lake</a> in <a href="/wiki/San_Marcelino,_Zambales" class="mw-redirect" title="San Marcelino, Zambales">San Marcelino, Zambales</a>, <a href="/wiki/Philippines" title="Philippines">Philippines</a>, is recovered, concluding <a href="/wiki/Search_and_rescue" title="Search and rescue">search operations</a> with the final death toll at nine. <a rel="nofollow" class="external text" href="https://newsinfo.inquirer.net/2295047/body-of-missing-pregnant-aeta-found-after-4-day-search-in-zambales-lake">(<i>Philippine Daily Inquirer</i>)</a></li></ul>
<p><b>International relations</b>
</p>
<ul><li><a href="/wiki/2026_state_visit_by_Xi_Jinping_to_Kyrgyzstan_and_Egypt" title="2026 state visit by Xi Jinping to Kyrgyzstan and Egypt">2026 state visit by Xi Jinping to Kyrgyzstan and Egypt</a>
<ul><li><a href="/wiki/China" title="China">Chinese</a> <a href="/wiki/Paramount_leader" title="Paramount leader">leader</a> <a href="/wiki/Xi_Jinping" title="Xi Jinping">Xi Jinping</a> and <a href="/wiki/First_Lady_of_China" title="First Lady of China">his wife</a> <a href="/wiki/Peng_Liyuan" title="Peng Liyuan">Peng Liyuan</a> arrive in <a href="/wiki/Bishkek" title="Bishkek">Bishkek</a>, <a href="/wiki/Kyrgyzstan" title="Kyrgyzstan">Kyrgyzstan</a>, for the <a href="/wiki/2026_Bishkek_SCO_summit" title="2026 Bishkek SCO summit">upcoming</a> <a href="/wiki/Shanghai_Cooperation_Organisation" title="Shanghai Cooperation Organisation">Shanghai Cooperation Organisation</a> summit and a <a href="/wiki/State_visit" title="State visit">state visit</a>. <a rel="nofollow" class="external text" href="https://www.rfi.fr/en/international-news/20260831-russia-s-putin-and-china-s-xi-to-attend-summit-in-kyrgyzstan">(AFP via RFI)</a> <a rel="nofollow" class="external text" href="https://english.news.cn/20260831/3ca97fc981694636957e9bcd18df2dfc/c.html">(Xinhua)</a></li></ul></li></ul>
`;
