// The songs, and the notation they are written in.
//
// This game ships no audio files. Every note is generated by the browser at
// play time, which is why the whole project is still a handful of text files.
// ADR 0004 says why. `audio.js` does the playing; this file is pure and holds
// only the notes, so the parser can be tested with no sound card in sight.
//
// Notation: a channel is one string of tokens separated by spaces.
//
//   "c4:4 e4:4 g4:8 r:4"
//
// Each token is a note name, then a colon, then how many sixteenths it lasts.
// `r` is a rest. A note name is a letter a to g, an optional `#` or `b`, then
// the octave number, so `f#3` and `bb4` are both fine. On the drum channel the
// names are `k` for kick, `s` for snare and `h` for hat.
//
// The music leans on highlife and Afrobeat: a pentatonic melody over an
// off-beat bass and a busy hat, rather than the march a Game Boy usually plays.

/** Semitone offsets from C, for every letter. */
const LETTERS = { c: 0, d: 2, e: 4, f: 5, g: 7, a: 9, b: 11 };

/** The drum sounds the noise channel knows. */
export const DRUMS = ["k", "s", "h"];

/**
 * Turn a note name into a frequency in hertz.
 * @returns {number|null} null for a name that is not a note
 */
export function noteFrequency(name) {
  const match = /^([a-g])([#b]?)(-?\d)$/i.exec(String(name ?? "").trim());
  if (!match) return null;
  const [, letter, accidental, octave] = match;
  let semitone = LETTERS[letter.toLowerCase()];
  if (accidental === "#") semitone += 1;
  if (accidental === "b") semitone -= 1;
  // Middle C is c4, and midi note 60. A4 is midi 69 and 440 hertz.
  const midi = (Number(octave) + 1) * 12 + semitone;
  return 440 * 2 ** ((midi - 69) / 12);
}

/**
 * Read one token.
 * @returns {{freq: number|null, drum: string|null, sixteenths: number}|null}
 *   null when the token cannot be read at all
 */
export function parseToken(token) {
  const text = String(token ?? "").trim();
  if (!text) return null;
  const [name, length] = text.split(":");
  const sixteenths = Number(length ?? 4);
  if (!Number.isFinite(sixteenths) || sixteenths <= 0) return null;
  if (name === "r") return { freq: null, drum: null, sixteenths };
  if (DRUMS.includes(name)) return { freq: null, drum: name, sixteenths };
  const freq = noteFrequency(name);
  if (freq === null) return null;
  return { freq, drum: null, sixteenths };
}

/**
 * Read a whole channel into notes with a start time in sixteenths.
 * A token that cannot be read is skipped, so one typo costs one note.
 * @returns {Array<{freq: number|null, drum: string|null, at: number, sixteenths: number}>}
 */
export function parseChannel(text) {
  const notes = [];
  let at = 0;
  for (const token of String(text ?? "").trim().split(/\s+/)) {
    const parsed = parseToken(token);
    if (!parsed) continue;
    notes.push({ ...parsed, at });
    at += parsed.sixteenths;
  }
  return notes;
}

/** How many sixteenths a channel lasts. */
export function channelLength(text) {
  const notes = parseChannel(text);
  if (notes.length === 0) return 0;
  const last = notes[notes.length - 1];
  return last.at + last.sixteenths;
}

/** How long one sixteenth lasts in seconds, at this tempo in beats per minute. */
export function sixteenthSeconds(bpm) {
  return 60 / Math.max(1, bpm) / 4;
}

/** How long a whole song lasts in seconds. */
export function songSeconds(song) {
  return songLength(song) * sixteenthSeconds(song.bpm);
}

/** The length of the longest channel, which is how long the loop is. */
export function songLength(song) {
  const lengths = (song.channels ?? []).map((channel) => channelLength(channel.notes));
  return lengths.length === 0 ? 0 : Math.max(...lengths);
}

/**
 * Every song in the game.
 *
 * A channel names the voice it wants:
 *   pulse   a square wave, for melody and counter-melody
 *   tri     a soft triangle, for the bass line
 *   noise   percussion, using the drum names above
 */
export const SONGS = {
  title: {
    bpm: 104,
    channels: [
      {
        voice: "pulse",
        gain: 0.16,
        duty: 0.5,
        notes:
          "g4:4 c5:4 e5:6 d5:2 c5:4 g4:4 a4:8 r:4 " +
          "f4:4 a4:4 c5:6 b4:2 a4:4 g4:4 g4:8 r:4",
      },
      {
        voice: "pulse",
        gain: 0.09,
        duty: 0.25,
        notes:
          "e4:4 g4:4 c5:6 b4:2 g4:4 e4:4 f4:8 r:4 " +
          "c4:4 f4:4 a4:6 g4:2 f4:4 e4:4 e4:8 r:4",
      },
      {
        voice: "tri",
        gain: 0.22,
        notes: "c3:8 c3:4 g2:4 f2:8 g2:8 f2:8 f2:4 c3:4 c3:8 g2:8",
      },
      {
        voice: "noise",
        gain: 0.1,
        notes: "h:4 h:4 s:4 h:4 h:4 h:4 s:4 h:4 h:4 h:4 s:4 h:4 h:4 h:4 s:4 h:4",
      },
    ],
  },

  town: {
    bpm: 132,
    channels: [
      {
        voice: "pulse",
        gain: 0.15,
        duty: 0.5,
        notes:
          "e5:2 g5:2 a5:4 g5:2 e5:2 d5:4 c5:2 d5:2 e5:4 d5:4 " +
          "c5:2 d5:2 e5:4 g5:2 a5:2 c6:4 a5:2 g5:2 e5:4 r:4",
      },
      {
        voice: "pulse",
        gain: 0.08,
        duty: 0.125,
        notes:
          "r:2 c5:2 r:2 e5:2 r:2 g5:2 r:2 e5:2 r:2 c5:2 r:2 e5:2 r:2 d5:2 r:2 g4:2 " +
          "r:2 c5:2 r:2 e5:2 r:2 a5:2 r:2 e5:2 r:2 c5:2 r:2 g4:2 r:2 c5:2 r:2 e5:2",
      },
      {
        voice: "tri",
        gain: 0.24,
        notes:
          "c3:4 r:2 c3:2 g2:4 r:2 g2:2 a2:4 r:2 a2:2 f2:4 r:2 f2:2 " +
          "c3:4 r:2 c3:2 g2:4 r:2 g2:2 f2:4 r:2 f2:2 g2:4 r:2 g2:2",
      },
      {
        voice: "noise",
        gain: 0.09,
        notes:
          "k:2 h:2 s:2 h:2 k:2 k:2 s:2 h:2 k:2 h:2 s:2 h:2 h:2 k:2 s:2 h:2 " +
          "k:2 h:2 s:2 h:2 k:2 k:2 s:2 h:2 k:2 h:2 s:2 h:2 h:2 k:2 s:2 h:2",
      },
    ],
  },

  route: {
    bpm: 146,
    channels: [
      {
        voice: "pulse",
        gain: 0.15,
        duty: 0.5,
        notes:
          "d5:2 f5:2 g5:2 a5:2 g5:4 f5:4 d5:2 c5:2 d5:4 r:2 a4:2 " +
          "c5:2 d5:2 f5:2 g5:2 a5:4 c6:4 a5:2 g5:2 f5:4 d5:4",
      },
      {
        voice: "pulse",
        gain: 0.08,
        duty: 0.25,
        notes:
          "a4:4 a4:4 d5:4 d5:4 c5:4 c5:4 a4:4 a4:4 " +
          "f4:4 f4:4 a4:4 a4:4 g4:4 g4:4 d4:4 d4:4",
      },
      {
        voice: "tri",
        gain: 0.24,
        notes:
          "d3:2 r:2 d3:2 a2:2 d3:2 r:2 f3:2 d3:2 " +
          "c3:2 r:2 c3:2 g2:2 c3:2 r:2 e3:2 c3:2 " +
          "f2:2 r:2 f2:2 c3:2 f2:2 r:2 a2:2 f2:2 " +
          "g2:2 r:2 g2:2 d3:2 g2:2 r:2 b2:2 g2:2",
      },
      {
        voice: "noise",
        gain: 0.09,
        notes:
          "k:2 h:1 h:1 s:2 h:2 k:2 h:2 s:2 h:1 h:1 " +
          "k:2 h:1 h:1 s:2 h:2 k:2 h:2 s:2 h:1 h:1",
      },
    ],
  },

  cave: {
    bpm: 96,
    channels: [
      {
        voice: "pulse",
        gain: 0.11,
        duty: 0.125,
        notes: "a4:6 c5:2 e5:8 d5:6 b4:2 a4:8 g4:6 a4:2 c5:8 a4:16",
      },
      {
        voice: "tri",
        gain: 0.26,
        notes: "a2:8 a2:8 f2:8 f2:8 g2:8 g2:8 a2:8 e2:8",
      },
      {
        voice: "noise",
        gain: 0.06,
        notes: "k:8 r:8 k:8 s:8 k:8 r:8 k:8 s:8",
      },
    ],
  },

  battle: {
    bpm: 168,
    channels: [
      {
        voice: "pulse",
        gain: 0.16,
        duty: 0.5,
        notes:
          "a4:2 a4:2 c5:2 e5:2 d5:4 c5:4 a4:2 a4:2 c5:2 d5:2 e5:8 " +
          "g5:2 f5:2 e5:2 d5:2 c5:4 a4:4 b4:2 c5:2 d5:2 e5:2 a4:8",
      },
      {
        voice: "pulse",
        gain: 0.09,
        duty: 0.25,
        notes:
          "e4:2 e4:2 a4:2 a4:2 g4:4 e4:4 e4:2 e4:2 a4:2 a4:2 c5:8 " +
          "e5:2 d5:2 c5:2 b4:2 a4:4 e4:4 g4:2 a4:2 b4:2 c5:2 e4:8",
      },
      {
        voice: "tri",
        gain: 0.26,
        notes:
          "a2:2 a2:2 a2:2 a2:2 f2:2 f2:2 f2:2 f2:2 " +
          "g2:2 g2:2 g2:2 g2:2 e2:2 e2:2 e2:2 e2:2 " +
          "a2:2 a2:2 a2:2 a2:2 f2:2 f2:2 f2:2 f2:2 " +
          "d2:2 d2:2 d2:2 d2:2 e2:2 e2:2 e2:2 e2:2",
      },
      {
        voice: "noise",
        gain: 0.1,
        notes:
          "k:2 h:2 s:2 h:2 k:2 h:2 s:2 h:1 h:1 " +
          "k:2 h:2 s:2 h:2 k:1 k:1 h:2 s:2 h:2",
      },
    ],
  },

  boss: {
    bpm: 178,
    channels: [
      {
        voice: "pulse",
        gain: 0.17,
        duty: 0.5,
        notes:
          "d5:2 d5:2 f5:2 d5:2 a5:4 g5:2 f5:2 e5:4 d5:4 " +
          "c5:2 c5:2 e5:2 c5:2 g5:4 f5:2 e5:2 d5:8",
      },
      {
        voice: "pulse",
        gain: 0.1,
        duty: 0.125,
        notes:
          "a4:2 a4:2 d5:2 a4:2 f5:4 e5:2 d5:2 c5:4 a4:4 " +
          "g4:2 g4:2 c5:2 g4:2 e5:4 d5:2 c5:2 a4:8",
      },
      {
        voice: "tri",
        gain: 0.28,
        notes:
          "d2:1 d2:1 d2:2 d2:1 d2:1 d2:2 a2:2 a2:2 f2:2 f2:2 " +
          "c2:1 c2:1 c2:2 c2:1 c2:1 c2:2 g2:2 g2:2 e2:2 e2:2",
      },
      {
        voice: "noise",
        gain: 0.12,
        notes: "k:1 k:1 h:2 s:2 h:2 k:1 k:1 h:2 s:2 h:1 h:1",
      },
    ],
  },

  victory: {
    bpm: 150,
    channels: [
      {
        voice: "pulse",
        gain: 0.17,
        duty: 0.5,
        notes: "c5:2 c5:2 c5:2 c5:6 g4:2 a4:2 c5:4 b4:2 c5:12",
      },
      {
        voice: "pulse",
        gain: 0.1,
        duty: 0.25,
        notes: "e4:2 e4:2 e4:2 e4:6 c4:2 f4:2 a4:4 g4:2 e4:12",
      },
      {
        voice: "tri",
        gain: 0.24,
        notes: "c3:8 c3:4 g2:2 a2:2 f2:4 g2:4 c3:8",
      },
      {
        voice: "noise",
        gain: 0.1,
        notes: "s:2 s:2 s:2 h:6 k:2 k:2 s:4 s:2 k:12",
      },
    ],
  },

  heal: {
    bpm: 120,
    channels: [
      {
        voice: "pulse",
        gain: 0.14,
        duty: 0.5,
        notes: "c5:2 e5:2 g5:2 c6:6",
      },
      {
        voice: "tri",
        gain: 0.2,
        notes: "c3:4 g3:4 c4:4",
      },
    ],
  },
};

/** Every song this game can play. */
export const SONG_IDS = Object.keys(SONGS);

/**
 * One song by name.
 * @returns {object|null} null when there is no song by that name
 */
export function getSong(id) {
  return SONGS[id] ?? null;
}

/**
 * The cry of one creature, worked out from its name.
 *
 * Twenty one hand-written cries would be twenty one more things to keep in
 * step with the species table. Instead the name itself picks the pitch, the
 * shape and the roughness, so every creature has its own voice, the voice never
 * changes, and a creature added later gets one for free.
 *
 * A heavy creature should sound heavy, so the caller passes its weight and a
 * low creature drops in pitch.
 *
 * @param {string} speciesId
 * @param {number} [weight] in kilograms, from the species table
 * @returns {{start:number, end:number, seconds:number, rough:number, wobble:number}}
 */
export function cryFor(speciesId, weight = 20) {
  let hash = 2166136261;
  for (const character of String(speciesId ?? "")) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  const pick = (shift, span) => ((hash >>> shift) & 0xff) / 255 * span;

  // A heavy creature growls; a light one chirps. The scale is generous because
  // the roster runs from a 0.4 kilogram fly to a 400 kilogram hippo.
  const heaviness = Math.min(1, Math.log10(Math.max(0.2, weight) + 1) / 2.7);
  const base = 520 - heaviness * 380 + pick(0, 160);
  const rise = pick(8, 1) > 0.5 ? 1 : -1;
  const end = Math.max(70, base * (1 + rise * (0.2 + pick(16, 0.45))));
  return {
    start: Math.max(70, base),
    end,
    seconds: 0.34 + pick(24, 0.22),
    rough: 0.15 + pick(4, 0.5),
    wobble: 6 + pick(12, 22),
  };
}
