// Build `words.js`, the list of words the page draws from.
//
// The page never runs this. Run it by hand when the list needs a refresh:
//
//   curl -O https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/es/es_50k.txt
//   curl -O https://dumps.wikimedia.org/eswiktionary/latest/eswiktionary-latest-pages-articles.xml.bz2
//   bun tools/buildWordList.js --frequency es_50k.txt --dump eswiktionary-latest-pages-articles.xml.bz2
//
// A word goes in the list when both of these hold:
// 1. It is among the `--top` most frequent words in the OpenSubtitles frequency
//    list (words people say out loud, not words people only read).
// 2. Its Spanish Wiktionary page calls it a lemma (not an inflected form) and
//    `isEligibleWord` finds a sense usable in Spain.
// 3. It is not mostly said as a form of a more frequent verb ("pongo", "debe"),
//    which `isFormOfCommonerVerb` checks against the same frequency list.
// See ADR 0001 for why the list lives in the repository and the definitions do not.

import { spawn } from "node:child_process";
import { createReadStream } from "node:fs";
import { writeFile } from "node:fs/promises";
import { createInterface } from "node:readline";
import { isCandidate, isEligibleWord, isFormOfCommonerVerb } from "../wikitext.js";

const args = Object.fromEntries(
  process.argv.slice(2).reduce((pairs, arg, index, all) => {
    if (arg.startsWith("--")) pairs.push([arg.slice(2), all[index + 1]]);
    return pairs;
  }, []),
);
const TOP = Number(args.top ?? 20000);
const OUT = new URL("../words.js", import.meta.url);

if (!args.frequency || !args.dump) {
  console.error("Usage: bun tools/buildWordList.js --frequency es_50k.txt --dump dump.xml[.bz2] [--top 20000]");
  process.exit(1);
}

/** Every word's place in the frequency list (1 = most frequent), and the candidates among the first `TOP`. */
async function readFrequency(path) {
  const rank = new Map();
  const candidates = [];
  for await (const line of createInterface({ input: createReadStream(path) })) {
    const word = line.split(" ")[0];
    if (!rank.has(word)) rank.set(word, rank.size + 1);
    if (rank.size <= TOP && isCandidate(word)) candidates.push(word);
  }
  return { rank, candidates };
}

/** Stream the dump, a line at a time, from a plain or a bzip2 file. */
function dumpLines(path) {
  const input = path.endsWith(".bz2") ? spawn("bzcat", [path]).stdout : createReadStream(path);
  return createInterface({ input, crlfDelay: Infinity });
}

const { rank, candidates } = await readFrequency(args.frequency);
const rankOf = (word) => rank.get(word) ?? Infinity;
const wanted = new Set(candidates);
const eligible = new Set();

let title = null;
let inText = false;
let text = [];
for await (const line of dumpLines(args.dump)) {
  const titleMatch = line.match(/^\s*<title>(.*)<\/title>$/);
  if (titleMatch) {
    title = wanted.has(titleMatch[1]) ? titleMatch[1] : null;
    continue;
  }
  if (!title) continue;
  if (!inText) {
    const start = line.indexOf("<text");
    if (start < 0) continue;
    const body = line.slice(line.indexOf(">", start) + 1);
    inText = true;
    text = [];
    if (body.endsWith("</text>")) {
      text.push(body.slice(0, -"</text>".length));
    } else {
      text.push(body);
      continue;
    }
  } else if (line.endsWith("</text>")) {
    text.push(line.slice(0, -"</text>".length));
  } else {
    text.push(line);
    continue;
  }
  inText = false;
  // The dump escapes the markup; the parser decodes the entities it reads.
  const wikitext = text.join("\n").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&amp;/g, "&");
  if (isEligibleWord(wikitext) && !isFormOfCommonerVerb(title, wikitext, rankOf)) eligible.add(title);
  title = null;
}

const words = candidates.filter((word) => eligible.has(word)).sort((a, b) => a.localeCompare(b, "es"));
const source = `// Generated by tools/buildWordList.js. Do not edit by hand; run the script again.
//
// ${words.length} common Spanish words, from the ${TOP} most frequent words in the
// OpenSubtitles list (hermitdave/FrequencyWords, CC BY-SA 4.0), kept when their
// Spanish Wiktionary page (CC BY-SA 4.0) has a sense usable in Spain.

export const WORDS = "${words.join(" ")}".split(" ");
`;
await writeFile(OUT, source);
console.log(`Wrote ${words.length} words to words.js (from ${candidates.length} candidates).`);
